name: Push-to-EC2 instance

# Trigger deployment only on deliverymans-assign branch 
on:
  push:
    branches:
      - deliverymans-assign
      - master

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            cd ~/dashboard
            ls 
            git clone https://github.com/medkhalilbk/tiktak-dashboard.git
            bash stopContainer.sh 3000
            mv ~/keys/serviceAccountKey.json ~/dashboard/src/lib/notifications/serviceAccountKey.json
            docker build -t dashboard-dev:latest .
            docker run -d -p 3000:3000 dashboard-dev:latest
            docker ps
            sudo systemctl restart nginx
